// Generated by CoffeeScript 1.7.1
(function() {
  var CarouselDemoCtrl, app,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  app = angular.module('myApp');

  CarouselDemoCtrl = (function(_super) {
    __extends(CarouselDemoCtrl, _super);

    function CarouselDemoCtrl() {
      return CarouselDemoCtrl.__super__.constructor.apply(this, arguments);
    }

    CarouselDemoCtrl.register(app, "CarouselDemoCtrl");

    CarouselDemoCtrl.inject('$scope');

    CarouselDemoCtrl.prototype.initialize = function() {
      this.$scope.slides = [];
      this.$scope.slides.push({
        text: 'cats!1',
        image: 'http://placekitten.com/300/200'
      });
      this.$scope.slides.push({
        text: 'cats!2',
        image: 'http://placekitten.com/301/200'
      });
      return this.$scope.slides.push({
        text: 'cats!3',
        image: 'http://placekitten.com/302/200'
      });
    };

    return CarouselDemoCtrl;

  })(BaseController);

}).call(this);
