// Generated by CoffeeScript 1.7.1
(function() {
  var ManuController, app,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  app = angular.module('myApp');

  ManuController = (function(_super) {
    var MENU_JSON_API_PATH;

    __extends(ManuController, _super);

    function ManuController() {
      return ManuController.__super__.constructor.apply(this, arguments);
    }

    ManuController.register(app, "MenuController");

    ManuController.inject('$scope', '$http');

    MENU_JSON_API_PATH = "api/menuJson";

    ManuController.prototype.initialize = function() {
      return this.loadMenuJson();
    };

    ManuController.prototype.loadMenuJson = function() {
      return this.$http.get(MENU_JSON_API_PATH).success(response)((function(_this) {
        return function() {
          return _this.$scope.menuJson = response;
        };
      })(this));
    };

    return ManuController;

  })(BaseController);

}).call(this);
