// Generated by CoffeeScript 1.7.1
(function() {
  var app, root;

  app = angular.module('myApp', ['ngRoute', 'ui.bootstrap']).config([
    '$routeProvider', function($routeProvider) {
      $routeProvider.when('/view1', {
        templateUrl: 'partials/partial1.html'
      });
      $routeProvider.when('/view2', {
        templateUrl: 'partials/partial2.html'
      });
      return $routeProvider.otherwise({
        redirectTo: '/view1'
      });
    }
  ]);

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  if (!root.app) {
    root.app = app;
  }

  angular.bootstrap(document, ['myApp']);

}).call(this);
