// Generated by CoffeeScript 1.7.1
(function() {
  window.MyCtrl1 = function() {};

  MyCtrl1.$inject = ['$scope'];

  window.MyCtrl2 = function() {};

  MyCtrl2.$inject = ['$scope'];

}).call(this);
